#Runs health check
#Currently scheduled to run once every year (1st of Jan) '0 0 1 1 *' 
#Change to e.g. '0 0 * * *' to be run every day at 00:00

name: Periodic healthcheck

on:
  schedule:
    - cron: '0 0 1 1 *' 

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: healthcheck
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://anekdootit-fullstack2022.herokuapp.com/health
#      - name: Periodic health check success
#        uses: rjstone/discord-webhook-notify@v1
#        if: success()
#        with:
#          severity: info
#          details: Periodic health check SUCCESS
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
#      - name: Periodic health check fail
#        uses: rjstone/discord-webhook-notify@v1
#        if: failure()
#        with:
#          severity: error
#          details: Periodic health check FAILED
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}